image: docker:20.10.16

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:20.10.16-dind

stages:
  - build

before_script:
  - docker info
  - printenv
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build_image:
  stage: build
  tags:
    - dind
  script:
    - if [ "$CI_COMMIT_TAG" != "" ]; then DOCKER_TAG=$CI_COMMIT_TAG; elif [ "$CI_COMMIT_BRANCH" != "master" ] && [ "$CI_COMMIT_BRANCH" != "main" ]; then DOCKER_TAG="$CI_COMMIT_BRANCH"; else DOCKER_TAG="latest"; fi
    - docker build -t $CI_REGISTRY_IMAGE:$DOCKER_TAG -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$DOCKER_TAG
    - if [ "$CI_COMMIT_TAG" = "" ]; then docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA; fi
